import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {createKart} from './kart';
import {Flag, Trophy, Timer, Users, Wrench, ArrowRight, ChevronLeft, Volume2, VolumeX, Sparkles, Sun, Waves} from 'lucide-react';
import './game.css';

function Showroom({color}:{color:string}){
 const host=useRef<HTMLDivElement>(null);const paint=useRef<THREE.MeshStandardMaterial|null>(null);
 useEffect(()=>{paint.current?.color.set(color);},[color]);
 useEffect(()=>{
  const el=host.current!;const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0,0);el.append(renderer.domElement);
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,2000);camera.position.set(180,125,240);camera.lookAt(0,10,0);
  scene.add(new THREE.HemisphereLight(0xe2fbff,0x367696,3));const light=new THREE.DirectionalLight(0xffffff,4);light.position.set(70,150,100);scene.add(light);
  const kart=createKart(color);paint.current=kart.userData.paint;scene.add(kart);
  const base=new THREE.Mesh(new THREE.CylinderGeometry(96,102,8,80),new THREE.MeshStandardMaterial({color:0xf2fbff,metalness:.3,roughness:.4}));base.position.y=-22;scene.add(base);
  const ring=new THREE.Mesh(new THREE.TorusGeometry(97,1.3,8,100),new THREE.MeshBasicMaterial({color:0x8af7e1}));ring.rotation.x=Math.PI/2;ring.position.y=-18;scene.add(ring);
  const resize=new ResizeObserver(()=>{renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();});resize.observe(el);
  let raf=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const loop=(t:number)=>{kart.rotation.y=reduced?-.4:Math.sin(t*.00022)*.55-.4;renderer.render(scene,camera);raf=requestAnimationFrame(loop);};raf=requestAnimationFrame(loop);
  return()=>{cancelAnimationFrame(raf);resize.disconnect();scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());}});renderer.dispose();el.replaceChildren();paint.current=null;};
 },[]);
 return <div className="showroom" ref={host} role="img" aria-label="Rotating 3D kart on a showroom platform"/>;
}
const cups=[{name:'Sunbeam Cup',icon:'☀',place:'PALM COAST',tone:'#ffbd47',tracks:['Palm Coast','Tidal Tunnel','Mango Mountain','Sunset Speedway']},{name:'Tidepool Cup',icon:'≈',place:'CORAL COVE',tone:'#40e2db',tracks:['Coral Cove','Pearl Pier','Blue Lagoon','Ocean Drive']},{name:'Starlight Cup',icon:'✦',place:'LUNAR LOOP',tone:'#b1a0ff',tracks:['Lunar Loop','Comet Crossing','Orbit Outpost','Midnight Mile']}];
export function GameUI(){
 const [page,setPage]=useState<'home'|'cups'|'garage'|'race'>('home');const [cup,setCup]=useState(0);const [color,setColor]=useState('#ff644b');const [engine,setEngine]=useState('150');const [mode,setMode]=useState('Grand Prix');const [count,setCount]=useState(3);const [quiet,setQuiet]=useState(false);
 useEffect(()=>{if(page!=='race')return;setCount(3);const timer=setInterval(()=>setCount(n=>Math.max(0,n-1)),1000);return()=>clearInterval(timer);},[page]);
 useEffect(()=>{document.title='Apex Island | Karting Club';const key=(e:KeyboardEvent)=>{if(e.key==='Escape'||e.key.toLowerCase()==='b')setPage('home');if(e.key.toLowerCase()==='a'&&document.activeElement instanceof HTMLButtonElement)document.activeElement.click();if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>('.island-game section button'));const index=buttons.indexOf(document.activeElement as HTMLButtonElement);buttons[(index+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length]?.focus();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{if(quiet)return;const click=()=>{const ctx=new AudioContext();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.frequency.setValueAtTime(620,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(940,ctx.currentTime+.07);gain.gain.setValueAtTime(.035,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.1);osc.start();osc.stop(ctx.currentTime+.11);osc.onended=()=>{void ctx.close();};};const el=document.querySelector('.island-game');el?.addEventListener('click',click);return()=>el?.removeEventListener('click',click);},[quiet]);
 const start=(name:string)=>{setMode(name);setPage('cups');};
 return <div className="island-game">
  <div className="island-sky"><div className="sun-disc"/><div className="cloud cloud-one"/><div className="cloud cloud-two"/><div className="island-mountain mountain-one"/><div className="island-mountain mountain-two"/><div className="ocean"/><div className="coast-road"/></div>
  <header className="island-header"><a className="island-logo" href="/game">APEX<span>ISLAND<span className="logo-star">✦</span></span><small>KARTING CLUB</small></a><div className="island-profile"><span className="profile-face">✦</span><div>NOVA<small>ROOKIE RACER · LV. 08</small></div><span className="coin-count">◈ 1,280</span></div></header>
  <nav className="island-breadcrumb"><button onClick={()=>setPage('home')}>PLAY</button><span>/</span><span>{page==='home'?'LET’S GO RACING':page==='garage'?'YOUR GARAGE':page==='race'?'RACE PREVIEW':'CHOOSE YOUR CUP'}</span><a href="/">UI lab ↗</a></nav>
  {page==='home'?<section className="game-home"><div className="game-menu"><div className="game-eyebrow">A LITTLE DRIFT. A LOT OF ADVENTURE.</div><h1>Good times.<br/><span>Full throttle.</span></h1><div className="race-menu">{[{name:'Grand Prix',sub:'Four tracks. One shiny trophy.',icon:Trophy},{name:'Time Attack',sub:'You, the clock, and the perfect lap.',icon:Timer},{name:'Local Versus',sub:'Make some friendly rivals.',icon:Users}].map(({name,sub,icon:Icon},i)=><button key={name} className={`mode-card mode-${i}`} onClick={()=>start(name)}><span className="mode-icon"><Icon/></span><span>{name}<small>{sub}</small></span><ArrowRight/></button>)}<button className="garage-button" onClick={()=>setPage('garage')}><Wrench size={19}/> Tune your ride <ArrowRight size={18}/></button></div></div><div className="hero-kart"><div className="kart-orbit">BUILT FOR THE GOOD TIMES</div><Showroom color={color}/><div className="kart-caption"><span>01 / CLUB ORIGINALS</span><h2>THE DAYTRIPPER</h2><p>Small kart. Big main-character energy.</p><button onClick={()=>setPage('garage')}>Make it yours <ArrowRight size={16}/></button></div></div><div className="island-news"><Sun/><span>THE COAST IS CALLING<small>3 cups · 12 destinations · endless detours</small></span><span className="news-tag">ISLAND TOUR</span></div></section>:
  page==='garage'?<section className="garage-screen"><div><div className="game-eyebrow">LOOK GOOD. DRIVE HAPPY.</div><h1>Your ride.<br/><span>Your rules.</span></h1><h2>The Daytripper</h2><p>Balanced handling for every kind of adventure.</p><div className="paint-options">{['#ff644b','#22d3bd','#ffc943','#8595ff','#f2f7fb'].map(c=><button aria-label={`Paint ${c}`} aria-pressed={c===color} key={c} style={{background:c}} onClick={()=>setColor(c)}>{c===color?'✓':''}</button>)}</div>{['Speed','Acceleration','Handling'].map((s,i)=><div className="kart-stat" key={s}><span>{s}</span><div>{Array.from({length:6},(_,n)=><i key={n} className={n<4+i%2?'filled':''}/>)}</div></div>)}<button className="island-primary" onClick={()=>setPage('home')}>Looking good! <ArrowRight/></button></div><Showroom color={color}/></section>:
  page==='cups'?<section className="cup-screen"><div className="cup-heading"><div><div className="game-eyebrow">{mode.toUpperCase()} / ISLAND TOUR</div><h1>Pick your <span>paradise.</span></h1></div><div className="engine-options" aria-label="Engine class">{['50','100','150','200'].map(v=><button aria-pressed={v===engine} key={v} onClick={()=>setEngine(v)}>{v}<small>cc</small></button>)}</div></div><div className="cup-grid">{cups.map((c,i)=><button key={c.name} onClick={()=>setCup(i)} className={`cup-card ${cup===i?'chosen':''}`} style={{'--cup-color':c.tone} as React.CSSProperties}><span className="cup-medal">{c.icon}</span><small>0{i+1} / ISLAND TOUR</small><h2>{c.name}</h2><span className="cup-stars">☆ ☆ ☆</span><span className="cup-select">{cup===i?'SELECTED':'EXPLORE CUP'} <ArrowRight size={16}/></span></button>)}</div><div className="track-strip">{cups[cup].tracks.map((t,i)=><div key={t}><span>0{i+1}</span><Waves/><b>{t}</b></div>)}</div><div className="cup-bottom"><p><Flag size={18}/> {engine}cc · {mode==='Local Versus'?'2 local racers':'1 player'} · 4 races</p><button className="island-primary" onClick={()=>setPage('race')}>Let’s race! <ArrowRight/></button></div></section>:
  <section className="race-screen"><div className="race-location"><small>{cups[cup].name} / RACE 01</small><h1>{cups[cup].tracks[0]}</h1></div><div className="race-position">1<small>st</small></div><Showroom color={color}/><div className="race-count">{count||'GO!'}</div><div className="race-lap">LAP <b>1 / 3</b></div><div className="preview-note">Interactive UI mockup · Race simulation coming later<button onClick={()=>setPage('cups')}>Choose another course</button></div></section>}
  <footer className="island-footer"><button onClick={()=>setPage('home')}><kbd>B</kbd> Back</button><span><kbd>↔</kbd> Choose <kbd>A</kbd> Select</span><span className="footer-right"><Sparkles size={15}/> EVERYONE’S A RACER <button aria-label={quiet?'Enable menu sound preference':'Mute menu sound preference'} onClick={()=>setQuiet(v=>!v)}>{quiet?<VolumeX size={20}/>:<Volume2 size={20}/>}</button></span></footer>
 </div>;
}
