import React,{useCallback,useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft,ArrowRight,Check,ChevronDown,Code2,Flag,Maximize2,Minimize2,Pause,Play,RotateCcw,Settings2,SkipBack,SkipForward,X} from 'lucide-react';
import {RacingLeaderboard} from './RacingLeaderboard';
import {DEFAULT_PLAYERS,DURATION,FIXED_STEP,MAX_FIXED_STEPS,referenceSelected} from './timeline';
import './styles.css';

function App(){
 const initialFrame=Math.max(0,Math.min(88,Number(new URLSearchParams(location.search).get('frame'))||0));
 const [time,setTime]=useState(initialFrame/30);const [playing,setPlaying]=useState(!new URLSearchParams(location.search).has('frame')&&!matchMedia('(prefers-reduced-motion: reduce)').matches);
 const [mode,setMode]=useState<'replay'|'interactive'>('replay');const [selected,setSelected]=useState(2);
 const [interaction,setInteraction]=useState<{id:number;index:number;type:'open'|'confirm'}>({id:0,index:2,type:'open'});
 const [players,setPlayers]=useState(DEFAULT_PLAYERS);const [settings,setSettings]=useState(false);
 const [compare,setCompare]=useState(false);const [referenceAvailable,setReferenceAvailable]=useState(false);const [split,setSplit]=useState(50);const [clean,setClean]=useState(new URLSearchParams(location.search).has('hud'));
 const [karts,setKarts]=useState(true);const [gloss,setGloss]=useState(1);const [speed,setSpeed]=useState(1);
 const [sheenStrength,setSheenStrength]=useState(1);const [sheenOpacity,setSheenOpacity]=useState(.86);const [sheenColor,setSheenColor]=useState('#dce8ff');const [bloom,setBloom]=useState(.45);
 const [reduced,setReduced]=useState(matchMedia('(prefers-reduced-motion: reduce)').matches);const [copied,setCopied]=useState(false);
 useEffect(()=>{const image=new Image();image.onload=()=>setReferenceAvailable(true);image.onerror=()=>setReferenceAvailable(false);image.src='./reference/0000.webp';return()=>{image.onload=null;image.onerror=null;};},[]);
 useEffect(()=>{if(!compare||!referenceAvailable)return;const images=Array.from({length:89},(_,i)=>{const image=new Image();image.src=`./reference/${String(i).padStart(4,'0')}.webp`;return image;});return()=>{images.length=0;};},[compare,referenceAvailable]);
 const active=mode==='replay'?referenceSelected(time):selected;
 const choose=useCallback((i:number)=>{setInteraction(event=>({id:event.id+1,index:i,type:mode==='interactive'&&i===selected?'confirm':'open'}));setSelected(i);setMode('interactive');setCompare(false);setPlaying(false);},[mode,selected]);
 useEffect(()=>{if(!playing)return;let id=0;let last=performance.now();let accumulator=0;function tick(now:number){if(document.hidden){last=now;accumulator=0;}else{accumulator+=Math.min((now-last)/1000,.25);last=now;let steps=0;while(accumulator>=FIXED_STEP&&steps<MAX_FIXED_STEPS){accumulator-=FIXED_STEP;steps++;}if(steps===MAX_FIXED_STEPS)accumulator=0;if(steps>0)setTime(t=>(t+steps*FIXED_STEP*speed)%DURATION);}id=requestAnimationFrame(tick);}id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id);},[playing,speed]);
 useEffect(()=>{function key(e:KeyboardEvent){if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;
  if(e.key===' '&&mode==='replay'){e.preventDefault();setPlaying(p=>!p);}if(e.key==='Escape'){setClean(false);setSettings(false);setCompare(false);}
  if(/^[1-6]$/.test(e.key))choose(Number(e.key)-1);
  if(mode==='replay'&&(e.key==='ArrowRight'||e.key==='ArrowLeft')){e.preventDefault();setPlaying(false);setTime(t=>Math.max(0,Math.min(88/30,t+(e.key==='ArrowRight'?1:-1)/30)));}
 }window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[choose,mode]);
 const scrub=(t:number)=>{setPlaying(false);setTime(t);};
 async function copyConfig(){const config={players,selectedIndex:active,showKarts:karts,gloss,sheenStrength,sheenOpacity,sheenColor,bloom,reducedMotion:reduced};await navigator.clipboard.writeText(JSON.stringify(config,null,2));setCopied(true);setTimeout(()=>setCopied(false),1800);}
 return <div className={`app ${clean?'clean':''}`}>
  <header className="topbar">
   <div className="brand"><span className="brand-mark"><Flag size={19}/></span><span>RACE<span className="brand-light">ORDER</span><small>RACING INTERFACE / 01</small></span></div>
   <nav className="mode-switch" aria-label="Preview mode"><button className={mode==='replay'?'active':''} onClick={()=>{setMode('replay');setTime(0);setPlaying(!reduced);}}>Source video</button><button className={mode==='interactive'?'active':''} onClick={()=>{setInteraction(event=>({id:event.id+1,index:selected,type:'open'}));setMode('interactive');setCompare(false);setPlaying(false);}}>Live UI</button></nav>
   <div className="top-actions"><button className={`icon-button ${settings?'active':''}`} aria-label="Customize interface" title="Customize interface" onClick={()=>setSettings(s=>!s)}><Settings2 size={18}/></button><button className="icon-button" aria-label="Enter clean HUD view" title="Clean HUD view" onClick={()=>setClean(true)}><Maximize2 size={18}/></button></div>
  </header>
  <main>
   <div className="stage-heading"><div><span className="eyebrow">{mode==='replay'?'SOURCE ANALYSIS':'LIVE HUD'}</span><h1>Every position. <span>{mode==='replay'?'In motion.':'At a glance.'}</span></h1></div><span className="render-status"><i/> {mode==='replay'?'REFERENCE PLAYER':'WEBGL / 60 FPS'}</span></div>
   <section className={`stage ${compare?'comparing':''}`} aria-label="Racing UI preview">
    <div className="stage-corner top-left"/><div className="stage-corner bottom-right"/>
    <div className="stage-label"><span className="little-checker"/> {compare?'REFERENCE COMPARISON':'RACE POSITIONS'}<span>06 DRIVERS</span></div>
    <div className="board-wrap">
     <RacingLeaderboard players={players} selectedIndex={active} onSelect={choose} interaction={interaction} time={time} replay={mode==='replay'} showKarts={karts} gloss={gloss} sheenStrength={sheenStrength} sheenOpacity={sheenOpacity} sheenColor={sheenColor} bloom={bloom} reducedMotion={reduced}/>
     {compare&&referenceAvailable&&<><div className="reference-overlay" style={{clipPath:`inset(0 ${100-split}% 0 0)`}}><img src={`./reference/${String(Math.min(88,Math.floor(time*30))).padStart(4,'0')}.webp`} alt={`Original reference at frame ${Math.floor(time*30)}`}/></div><div className="compare-line" style={{left:`${split}%`}}><span><ArrowLeft size={12}/><ArrowRight size={12}/></span></div><input className="compare-slider" type="range" min="0" max="100" value={split} onChange={e=>setSplit(Number(e.target.value))} aria-label="Reference comparison divider"/><div className="compare-labels"><span>ORIGINAL</span><span>RECREATION</span></div></>}
    </div>
    <div className="stage-foot"><span><i/>{mode==='replay'?'SOURCE SEQUENCE':'LIVE INTERACTION'}<b>{mode==='replay'?'03 → 05 → 04':'CLICK A POSITION OR PRESS 1–6'}</b></span>{mode==='replay'?<button className={compare?'compare-button active':'compare-button'} disabled={!referenceAvailable} title={referenceAvailable?'Compare the local reference frames':'Add local frames in public/reference to enable comparison'} onClick={()=>referenceAvailable&&setCompare(c=>!c)}><span className="split-icon"/> {compare?'Exit comparison':'Compare source'}</button>:<span className="live-chip"><i/> WEBGL LIVE</span>}</div>
   </section>
   {mode==='replay'&&<section className="transport" aria-label="Animation playback">
    <div className="playback"><button className="icon-button" aria-label="Restart animation" onClick={()=>{setTime(0);setPlaying(!reduced);}}><RotateCcw size={17}/></button><button className="play-button" aria-label={playing?'Pause animation':'Play animation'} onClick={()=>setPlaying(p=>!p)}>{playing?<Pause size={18} fill="currentColor"/>:<Play size={18} fill="currentColor"/>}</button><div className="timecode">{time.toFixed(2)}<span>/ 2.97s</span></div></div>
    <div className="timeline"><input type="range" aria-label="Animation timeline" min="0" max={88/30} step={1/30} value={time} style={{'--progress':`${time/DURATION*100}%`} as React.CSSProperties} onChange={e=>scrub(Number(e.target.value))}/><div className="timeline-markers"><span>PLAYER 2</span><span>PLAYER 6</span><span>PLAYER 5</span><span>LIGHT SWEEP</span></div></div>
    <div className="frame-controls"><button className="icon-button" aria-label="Previous frame" onClick={()=>scrub(Math.max(0,time-1/30))}><SkipBack size={15}/></button><span>{String(Math.min(88,Math.floor(time*30))).padStart(2,'0')}<small> / 88</small></span><button className="icon-button" aria-label="Next frame" onClick={()=>scrub(Math.min(88/30,time+1/30))}><SkipForward size={15}/></button><label className="speed-control"><select aria-label="Playback speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value="0.25">0.25×</option><option value="0.5">0.5×</option><option value="1">1×</option><option value="1.5">1.5×</option></select><ChevronDown size={12}/></label></div>
   </section>}
   <footer><span>REACT + WEBGL <b>·</b> PROCEDURAL MATERIALS <b>·</b> LIVE 3D</span><span>{mode==='replay'?<><kbd>SPACE</kbd> play / pause <kbd>← →</kbd> frame step</>:<><kbd>1—6</kbd> select driver <kbd>ESC</kbd> close panels</>}</span></footer>
  </main>
  {clean&&<button className="exit-clean icon-button" aria-label="Exit clean HUD view" onClick={()=>setClean(false)}><Minimize2 size={20}/></button>}
  {settings&&<><button className="panel-backdrop" aria-label="Close customization panel" onClick={()=>setSettings(false)}/><aside className="settings-panel" aria-label="Customize interface"><div className="panel-title"><div><span className="eyebrow">MAKE IT YOURS</span><h2>Interface settings</h2></div><button className="icon-button" aria-label="Close settings" onClick={()=>setSettings(false)}><X size={18}/></button></div><p>Fine-tune the HUD for your next race.</p><h3>Drivers</h3><div className="driver-inputs">{players.map((p,i)=><div key={p.id}><span>{String(i+1).padStart(2,'0')}</span><input aria-label={`Position ${i+1} color`} type="color" value={p.color} onChange={e=>setPlayers(ps=>ps.map((v,n)=>n===i?{...v,color:e.target.value}:v))}/><input aria-label={`Position ${i+1} driver name`} value={p.name} maxLength={24} onChange={e=>setPlayers(ps=>ps.map((v,n)=>n===i?{...v,name:e.target.value}:v))}/></div>)}</div><h3>Appearance</h3><label className="setting-line">3D karts<input type="checkbox" role="switch" checked={karts} onChange={e=>setKarts(e.target.checked)}/></label><label className="setting-line">Reduce motion<input type="checkbox" role="switch" checked={reduced} onChange={e=>{setReduced(e.target.checked);if(e.target.checked)setPlaying(false);}}/></label><label className="gloss-label">Surface gloss <span>{Math.round(gloss*100)}%</span><input aria-label="Surface gloss" type="range" min="0" max="1.5" step=".05" value={gloss} onChange={e=>setGloss(Number(e.target.value))}/></label><h3>Light motion</h3><label className="gloss-label">Woosh strength <span>{Math.round(sheenStrength*100)}%</span><input aria-label="Woosh strength" type="range" min="0" max="2" step=".05" value={sheenStrength} onChange={e=>setSheenStrength(Number(e.target.value))}/></label><label className="gloss-label">Woosh opacity <span>{Math.round(sheenOpacity*100)}%</span><input aria-label="Woosh opacity" type="range" min="0" max="1" step=".01" value={sheenOpacity} onChange={e=>setSheenOpacity(Number(e.target.value))}/></label><label className="color-setting">Woosh color <span><input aria-label="Woosh color" type="color" value={sheenColor} onChange={e=>setSheenColor(e.target.value)}/><code>{sheenColor.toUpperCase()}</code></span></label><label className="gloss-label">Bloom <span>{Math.round(bloom*100)}%</span><input aria-label="Bloom" type="range" min="0" max="1.2" step=".05" value={bloom} onChange={e=>setBloom(Number(e.target.value))}/></label><button className="export-button" onClick={copyConfig}>{copied?<Check size={16}/>:<Code2 size={16}/>} {copied?'Configuration copied':'Copy configuration'}</button><button className="reset-button" onClick={()=>{setPlayers(DEFAULT_PLAYERS);setKarts(true);setGloss(1);setSheenStrength(1);setSheenOpacity(.86);setSheenColor('#dce8ff');setBloom(.45);}}>Reset appearance</button><div className="panel-note">Use the standalone leaderboard component to connect your game’s driver and position data.</div></aside></>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
